// Code generated by protoc-gen-go. DO NOT EDIT.
// source: UserPosition.proto

/*
Package objects is a generated protocol buffer package.

It is generated from these files:
	UserPosition.proto

It has these top-level messages:
	UserLocationValue
	UserLocation
	UserFence
*/
package objects

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import pmc "github.com/AsT4re/zen/libs/producingmessageconsumer"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserLocationValue struct {
	UserId uint32  `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	Lat    float64 `protobuf:"fixed64,2,opt,name=lat" json:"lat,omitempty"`
	Long   float64 `protobuf:"fixed64,3,opt,name=long" json:"long,omitempty"`
}

func (m *UserLocationValue) Reset()                    { *m = UserLocationValue{} }
func (m *UserLocationValue) String() string            { return proto.CompactTextString(m) }
func (*UserLocationValue) ProtoMessage()               {}
func (*UserLocationValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserLocationValue) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserLocationValue) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *UserLocationValue) GetLong() float64 {
	if m != nil {
		return m.Long
	}
	return 0
}

type UserLocation struct {
	Metas *pmc.MessageMetadatas `protobuf:"bytes,1,opt,name=metas" json:"metas,omitempty"`
	Value *UserLocationValue    `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *UserLocation) Reset()                    { *m = UserLocation{} }
func (m *UserLocation) String() string            { return proto.CompactTextString(m) }
func (*UserLocation) ProtoMessage()               {}
func (*UserLocation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserLocation) GetMetas() *pmc.MessageMetadatas {
	if m != nil {
		return m.Metas
	}
	return nil
}

func (m *UserLocation) GetValue() *UserLocationValue {
	if m != nil {
		return m.Value
	}
	return nil
}

type UserFence struct {
	UserId    uint32 `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	PlaceName string `protobuf:"bytes,2,opt,name=placeName" json:"placeName,omitempty"`
}

func (m *UserFence) Reset()                    { *m = UserFence{} }
func (m *UserFence) String() string            { return proto.CompactTextString(m) }
func (*UserFence) ProtoMessage()               {}
func (*UserFence) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UserFence) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserFence) GetPlaceName() string {
	if m != nil {
		return m.PlaceName
	}
	return ""
}

func init() {
	proto.RegisterType((*UserLocationValue)(nil), "objects.UserLocationValue")
	proto.RegisterType((*UserLocation)(nil), "objects.UserLocation")
	proto.RegisterType((*UserFence)(nil), "objects.UserFence")
}

func init() { proto.RegisterFile("UserPosition.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x89, 0xb5, 0x95, 0x9d, 0x2a, 0xe8, 0x80, 0x65, 0x29, 0x1e, 0xca, 0x9e, 0x0a, 0x42,
	0x90, 0xfa, 0x0b, 0xbc, 0x08, 0x82, 0x15, 0x0d, 0xe8, 0x7d, 0x9a, 0x0e, 0xa5, 0x92, 0x6c, 0x96,
	0x9d, 0xd4, 0xdf, 0x2f, 0x49, 0x16, 0x14, 0xa5, 0xb7, 0xc9, 0xcb, 0x7b, 0x2f, 0x5f, 0x06, 0xf0,
	0x5d, 0xb8, 0x7f, 0x0d, 0xb2, 0x8f, 0xfb, 0xd0, 0xea, 0xae, 0x0f, 0x31, 0xe0, 0x59, 0xd8, 0x7c,
	0xb2, 0x8d, 0x32, 0x9f, 0xad, 0x59, 0x84, 0x76, 0xbc, 0xe6, 0x48, 0x5b, 0x8a, 0x24, 0xc5, 0xd0,
	0xbc, 0xc1, 0x55, 0x8a, 0x3d, 0x07, 0x4b, 0x29, 0xf6, 0x41, 0xee, 0xc0, 0x38, 0x83, 0xc9, 0x41,
	0xb8, 0x7f, 0xda, 0xd6, 0x6a, 0xa1, 0x96, 0x17, 0x66, 0x38, 0xe1, 0x25, 0x8c, 0x1c, 0xc5, 0xfa,
	0x64, 0xa1, 0x96, 0xca, 0xa4, 0x11, 0x11, 0x4e, 0x5d, 0x68, 0x77, 0xf5, 0x28, 0x4b, 0x79, 0x6e,
	0x3c, 0x9c, 0xff, 0xae, 0xc4, 0x5b, 0x18, 0x7b, 0x8e, 0x24, 0xb9, 0x6c, 0xba, 0xba, 0xd6, 0x9d,
	0xb7, 0xfa, 0x2f, 0x8e, 0x29, 0x1e, 0xbc, 0x83, 0xf1, 0x57, 0x62, 0xc8, 0x8f, 0x4c, 0x57, 0x73,
	0x3d, 0x7c, 0x40, 0xff, 0xa3, 0x34, 0xc5, 0xd8, 0x3c, 0x40, 0x95, 0xee, 0x1e, 0xb9, 0xb5, 0xc7,
	0xc9, 0x6f, 0xa0, 0xea, 0x1c, 0x59, 0x7e, 0x21, 0x5f, 0xaa, 0x2b, 0xf3, 0x23, 0x6c, 0x26, 0x79,
	0x17, 0xf7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x91, 0x78, 0xde, 0xed, 0x42, 0x01, 0x00, 0x00,
}
